# Generated by Django 5.0 on 2023-12-28 05:00

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("price", models.FloatField()),
                ("cat", models.CharField(max_length=50)),
                ("pdetail", models.CharField(max_length=300)),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
    ]
