# Generated by Django 5.0 on 2023-12-28 05:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ecomapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="cat",
            field=models.IntegerField(max_length=50),
        ),
    ]
