# Generated by Django 5.0 on 2024-01-03 03:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ecomapp", "0002_alter_product_cat"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="pimage",
            field=models.ImageField(default=0, upload_to="image"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="product",
            name="cat",
            field=models.IntegerField(
                choices=[(1, "Mobile"), (2, "Shoes"), (3, "Cloths")],
                max_length=50,
                verbose_name="Category",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(max_length=50, verbose_name="Product Name"),
        ),
        migrations.AlterField(
            model_name="product",
            name="pdetail",
            field=models.CharField(max_length=300, verbose_name="Product Details"),
        ),
    ]
