# Generated by Django 5.0 on 2024-01-03 04:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ecomapp", "0005_alter_cart_pid_alter_cart_userid"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cart",
            old_name="userid",
            new_name="uid",
        ),
    ]
