# Generated by Django 5.0 on 2024-01-04 04:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ecomapp", "0006_rename_userid_cart_uid"),
    ]

    operations = [
        migrations.AddField(
            model_name="cart",
            name="qty",
            field=models.IntegerField(default=1),
        ),
    ]
