# Generated by Django 5.0 on 2024-01-04 05:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ecomapp", "0008_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="orderid",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
