# Generated by Django 5.0 on 2024-01-15 19:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ecomapp", "0010_order_amt"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="age",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="product",
            name="cat",
            field=models.IntegerField(
                choices=[
                    (1, "Beagle"),
                    (2, "Bulldog"),
                    (3, "German Shepherd"),
                    (4, "Poddle"),
                    (5, "English Springer Spaniel"),
                    (6, "Airedale Terrier"),
                ],
                max_length=50,
                verbose_name="Category",
            ),
        ),
    ]
